//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	networkingv1 "k8s.io/api/networking/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/intstr"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSNodePoolSpec) DeepCopyInto(out *AWSNodePoolSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSNodePoolSpec.
func (in *AWSNodePoolSpec) DeepCopy() *AWSNodePoolSpec {
	if in == nil {
		return nil
	}
	out := new(AWSNodePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControlSpec) DeepCopyInto(out *AccessControlSpec) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControlSpec.
func (in *AccessControlSpec) DeepCopy() *AccessControlSpec {
	if in == nil {
		return nil
	}
	out := new(AccessControlSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureNodePoolSpec) DeepCopyInto(out *AzureNodePoolSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureNodePoolSpec.
func (in *AzureNodePoolSpec) DeepCopy() *AzureNodePoolSpec {
	if in == nil {
		return nil
	}
	out := new(AzureNodePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BigQueryCatalogSpec) DeepCopyInto(out *BigQueryCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BigQueryCatalogSpec.
func (in *BigQueryCatalogSpec) DeepCopy() *BigQueryCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(BigQueryCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlackHoleCatalogSpec) DeepCopyInto(out *BlackHoleCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlackHoleCatalogSpec.
func (in *BlackHoleCatalogSpec) DeepCopy() *BlackHoleCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(BlackHoleCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraCatalogSpec) DeepCopyInto(out *CassandraCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraCatalogSpec.
func (in *CassandraCatalogSpec) DeepCopy() *CassandraCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(CassandraCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogPropertySecretRefs) DeepCopyInto(out *CatalogPropertySecretRefs) {
	*out = *in
	if in.PropertySecretRefs != nil {
		in, out := &in.PropertySecretRefs, &out.PropertySecretRefs
		*out = make(map[string]corev1.SecretKeySelector, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogPropertySecretRefs.
func (in *CatalogPropertySecretRefs) DeepCopy() *CatalogPropertySecretRefs {
	if in == nil {
		return nil
	}
	out := new(CatalogPropertySecretRefs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClickHouseCatalogSpec) DeepCopyInto(out *ClickHouseCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.ConnectionPasswordSecret != nil {
		in, out := &in.ConnectionPasswordSecret, &out.ConnectionPasswordSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClickHouseCatalogSpec.
func (in *ClickHouseCatalogSpec) DeepCopy() *ClickHouseCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(ClickHouseCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoordinatorHelmConfigSpec) DeepCopyInto(out *CoordinatorHelmConfigSpec) {
	*out = *in
	if in.SecretMounts != nil {
		in, out := &in.SecretMounts, &out.SecretMounts
		*out = make([]SecretMountSpec, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalConfigFiles != nil {
		in, out := &in.AdditionalConfigFiles, &out.AdditionalConfigFiles
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoordinatorHelmConfigSpec.
func (in *CoordinatorHelmConfigSpec) DeepCopy() *CoordinatorHelmConfigSpec {
	if in == nil {
		return nil
	}
	out := new(CoordinatorHelmConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomCatalogSpec) DeepCopyInto(out *CustomCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomCatalogSpec.
func (in *CustomCatalogSpec) DeepCopy() *CustomCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(CustomCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeltaLakeCatalogSpec) DeepCopyInto(out *DeltaLakeCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeltaLakeCatalogSpec.
func (in *DeltaLakeCatalogSpec) DeepCopy() *DeltaLakeCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(DeltaLakeCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DruidCatalogSpec) DeepCopyInto(out *DruidCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DruidCatalogSpec.
func (in *DruidCatalogSpec) DeepCopy() *DruidCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(DruidCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DuckDBCatalogSpec) DeepCopyInto(out *DuckDBCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DuckDBCatalogSpec.
func (in *DuckDBCatalogSpec) DeepCopy() *DuckDBCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(DuckDBCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchCatalogSpec) DeepCopyInto(out *ElasticsearchCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchCatalogSpec.
func (in *ElasticsearchCatalogSpec) DeepCopy() *ElasticsearchCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExasolCatalogSpec) DeepCopyInto(out *ExasolCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.ConnectionPasswordSecret != nil {
		in, out := &in.ConnectionPasswordSecret, &out.ConnectionPasswordSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExasolCatalogSpec.
func (in *ExasolCatalogSpec) DeepCopy() *ExasolCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(ExasolCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExchangeManagerSpec) DeepCopyInto(out *ExchangeManagerSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.BaseDirectories != nil {
		in, out := &in.BaseDirectories, &out.BaseDirectories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExchangeManagerSpec.
func (in *ExchangeManagerSpec) DeepCopy() *ExchangeManagerSpec {
	if in == nil {
		return nil
	}
	out := new(ExchangeManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FakerCatalogSpec) DeepCopyInto(out *FakerCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FakerCatalogSpec.
func (in *FakerCatalogSpec) DeepCopy() *FakerCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(FakerCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FaultTolerantExecutionSpec) DeepCopyInto(out *FaultTolerantExecutionSpec) {
	*out = *in
	if in.ExchangeManager != nil {
		in, out := &in.ExchangeManager, &out.ExchangeManager
		*out = new(ExchangeManagerSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FaultTolerantExecutionSpec.
func (in *FaultTolerantExecutionSpec) DeepCopy() *FaultTolerantExecutionSpec {
	if in == nil {
		return nil
	}
	out := new(FaultTolerantExecutionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCPNodePoolSpec) DeepCopyInto(out *GCPNodePoolSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCPNodePoolSpec.
func (in *GCPNodePoolSpec) DeepCopy() *GCPNodePoolSpec {
	if in == nil {
		return nil
	}
	out := new(GCPNodePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleSheetsCatalogSpec) DeepCopyInto(out *GoogleSheetsCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleSheetsCatalogSpec.
func (in *GoogleSheetsCatalogSpec) DeepCopy() *GoogleSheetsCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(GoogleSheetsCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GracefulShutdownSpec) DeepCopyInto(out *GracefulShutdownSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GracefulShutdownSpec.
func (in *GracefulShutdownSpec) DeepCopy() *GracefulShutdownSpec {
	if in == nil {
		return nil
	}
	out := new(GracefulShutdownSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmChartConfigSpec) DeepCopyInto(out *HelmChartConfigSpec) {
	*out = *in
	if in.AccessControl != nil {
		in, out := &in.AccessControl, &out.AccessControl
		*out = new(AccessControlSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretMounts != nil {
		in, out := &in.SecretMounts, &out.SecretMounts
		*out = make([]SecretMountSpec, len(*in))
		copy(*out, *in)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(ServiceAccountSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkPolicy != nil {
		in, out := &in.NetworkPolicy, &out.NetworkPolicy
		*out = new(NetworkPolicySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceMonitor != nil {
		in, out := &in.ServiceMonitor, &out.ServiceMonitor
		*out = new(ServiceMonitorSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Coordinator != nil {
		in, out := &in.Coordinator, &out.Coordinator
		*out = new(CoordinatorHelmConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Worker != nil {
		in, out := &in.Worker, &out.Worker
		*out = new(WorkerHelmConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]corev1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InitContainers != nil {
		in, out := &in.InitContainers, &out.InitContainers
		*out = make(map[string][]corev1.Container, len(*in))
		for key, val := range *in {
			var outVal []corev1.Container
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]corev1.Container, len(*in))
				for i := range *in {
					(*in)[i].DeepCopyInto(&(*out)[i])
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmChartConfigSpec.
func (in *HelmChartConfigSpec) DeepCopy() *HelmChartConfigSpec {
	if in == nil {
		return nil
	}
	out := new(HelmChartConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HiveCatalogSpec) DeepCopyInto(out *HiveCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.S3AccessKeySecret != nil {
		in, out := &in.S3AccessKeySecret, &out.S3AccessKeySecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.S3SecretKeySecret != nil {
		in, out := &in.S3SecretKeySecret, &out.S3SecretKeySecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HiveCatalogSpec.
func (in *HiveCatalogSpec) DeepCopy() *HiveCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(HiveCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HudiCatalogSpec) DeepCopyInto(out *HudiCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HudiCatalogSpec.
func (in *HudiCatalogSpec) DeepCopy() *HudiCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(HudiCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IcebergCatalogSpec) DeepCopyInto(out *IcebergCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IcebergCatalogSpec.
func (in *IcebergCatalogSpec) DeepCopy() *IcebergCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(IcebergCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IgniteCatalogSpec) DeepCopyInto(out *IgniteCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.ConnectionPasswordSecret != nil {
		in, out := &in.ConnectionPasswordSecret, &out.ConnectionPasswordSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IgniteCatalogSpec.
func (in *IgniteCatalogSpec) DeepCopy() *IgniteCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(IgniteCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressHostSpec) DeepCopyInto(out *IngressHostSpec) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]IngressPathSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressHostSpec.
func (in *IngressHostSpec) DeepCopy() *IngressHostSpec {
	if in == nil {
		return nil
	}
	out := new(IngressHostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressPathSpec) DeepCopyInto(out *IngressPathSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressPathSpec.
func (in *IngressPathSpec) DeepCopy() *IngressPathSpec {
	if in == nil {
		return nil
	}
	out := new(IngressPathSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]IngressHostSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = make([]IngressTLSSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSpec.
func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressTLSSpec) DeepCopyInto(out *IngressTLSSpec) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressTLSSpec.
func (in *IngressTLSSpec) DeepCopy() *IngressTLSSpec {
	if in == nil {
		return nil
	}
	out := new(IngressTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JMXCatalogSpec) DeepCopyInto(out *JMXCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JMXCatalogSpec.
func (in *JMXCatalogSpec) DeepCopy() *JMXCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(JMXCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JMXExporterSpec) DeepCopyInto(out *JMXExporterSpec) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JMXExporterSpec.
func (in *JMXExporterSpec) DeepCopy() *JMXExporterSpec {
	if in == nil {
		return nil
	}
	out := new(JMXExporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KEDASpec) DeepCopyInto(out *KEDASpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Threshold != nil {
		in, out := &in.Threshold, &out.Threshold
		*out = new(string)
		**out = **in
	}
	if in.PrometheusServer != nil {
		in, out := &in.PrometheusServer, &out.PrometheusServer
		*out = new(string)
		**out = **in
	}
	if in.PrometheusQuery != nil {
		in, out := &in.PrometheusQuery, &out.PrometheusQuery
		*out = new(string)
		**out = **in
	}
	if in.HTTPEndpoint != nil {
		in, out := &in.HTTPEndpoint, &out.HTTPEndpoint
		*out = new(string)
		**out = **in
	}
	if in.HTTPValueLocation != nil {
		in, out := &in.HTTPValueLocation, &out.HTTPValueLocation
		*out = new(string)
		**out = **in
	}
	if in.ScaleDownCooldown != nil {
		in, out := &in.ScaleDownCooldown, &out.ScaleDownCooldown
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.ScaleUpCooldown != nil {
		in, out := &in.ScaleUpCooldown, &out.ScaleUpCooldown
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.JMXExporter != nil {
		in, out := &in.JMXExporter, &out.JMXExporter
		*out = new(JMXExporterSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KEDASpec.
func (in *KEDASpec) DeepCopy() *KEDASpec {
	if in == nil {
		return nil
	}
	out := new(KEDASpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KafkaCatalogSpec) DeepCopyInto(out *KafkaCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.KafkaNodes != nil {
		in, out := &in.KafkaNodes, &out.KafkaNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaCatalogSpec.
func (in *KafkaCatalogSpec) DeepCopy() *KafkaCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(KafkaCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LakehouseCatalogSpec) DeepCopyInto(out *LakehouseCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LakehouseCatalogSpec.
func (in *LakehouseCatalogSpec) DeepCopy() *LakehouseCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(LakehouseCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitsSpec) DeepCopyInto(out *LimitsSpec) {
	*out = *in
	if in.HardConcurrencyPerGroup != nil {
		in, out := &in.HardConcurrencyPerGroup, &out.HardConcurrencyPerGroup
		*out = new(int32)
		**out = **in
	}
	if in.MaxQueuedPerGroup != nil {
		in, out := &in.MaxQueuedPerGroup, &out.MaxQueuedPerGroup
		*out = new(int32)
		**out = **in
	}
	if in.Session != nil {
		in, out := &in.Session, &out.Session
		*out = new(SessionLimits)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitsSpec.
func (in *LimitsSpec) DeepCopy() *LimitsSpec {
	if in == nil {
		return nil
	}
	out := new(LimitsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LokiCatalogSpec) DeepCopyInto(out *LokiCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LokiCatalogSpec.
func (in *LokiCatalogSpec) DeepCopy() *LokiCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(LokiCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MariaDBCatalogSpec) DeepCopyInto(out *MariaDBCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.ConnectionPasswordSecret != nil {
		in, out := &in.ConnectionPasswordSecret, &out.ConnectionPasswordSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MariaDBCatalogSpec.
func (in *MariaDBCatalogSpec) DeepCopy() *MariaDBCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(MariaDBCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryCatalogSpec) DeepCopyInto(out *MemoryCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryCatalogSpec.
func (in *MemoryCatalogSpec) DeepCopy() *MemoryCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(MemoryCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoDBCatalogSpec) DeepCopyInto(out *MongoDBCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoDBCatalogSpec.
func (in *MongoDBCatalogSpec) DeepCopy() *MongoDBCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(MongoDBCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MySQLCatalogSpec) DeepCopyInto(out *MySQLCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.ConnectionPasswordSecret != nil {
		in, out := &in.ConnectionPasswordSecret, &out.ConnectionPasswordSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MySQLCatalogSpec.
func (in *MySQLCatalogSpec) DeepCopy() *MySQLCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(MySQLCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicyEgressSpec) DeepCopyInto(out *NetworkPolicyEgressSpec) {
	*out = *in
	if in.To != nil {
		in, out := &in.To, &out.To
		*out = make([]NetworkPolicyPeerSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]NetworkPolicyPortSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicyEgressSpec.
func (in *NetworkPolicyEgressSpec) DeepCopy() *NetworkPolicyEgressSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicyEgressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicyIngressSpec) DeepCopyInto(out *NetworkPolicyIngressSpec) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = make([]NetworkPolicyPeerSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]NetworkPolicyPortSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicyIngressSpec.
func (in *NetworkPolicyIngressSpec) DeepCopy() *NetworkPolicyIngressSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicyIngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicyPeerSpec) DeepCopyInto(out *NetworkPolicyPeerSpec) {
	*out = *in
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.IPBlock != nil {
		in, out := &in.IPBlock, &out.IPBlock
		*out = new(networkingv1.IPBlock)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicyPeerSpec.
func (in *NetworkPolicyPeerSpec) DeepCopy() *NetworkPolicyPeerSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicyPeerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicyPortSpec) DeepCopyInto(out *NetworkPolicyPortSpec) {
	*out = *in
	if in.Protocol != nil {
		in, out := &in.Protocol, &out.Protocol
		*out = new(corev1.Protocol)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicyPortSpec.
func (in *NetworkPolicyPortSpec) DeepCopy() *NetworkPolicyPortSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicyPortSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkPolicySpec) DeepCopyInto(out *NetworkPolicySpec) {
	*out = *in
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = make([]NetworkPolicyIngressSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = make([]NetworkPolicyEgressSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkPolicySpec.
func (in *NetworkPolicySpec) DeepCopy() *NetworkPolicySpec {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolSpec) DeepCopyInto(out *NodePoolSpec) {
	*out = *in
	if in.MinNodes != nil {
		in, out := &in.MinNodes, &out.MinNodes
		*out = new(int32)
		**out = **in
	}
	if in.MaxNodes != nil {
		in, out := &in.MaxNodes, &out.MaxNodes
		*out = new(int32)
		**out = **in
	}
	if in.Zones != nil {
		in, out := &in.Zones, &out.Zones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OSDiskGB != nil {
		in, out := &in.OSDiskGB, &out.OSDiskGB
		*out = new(int32)
		**out = **in
	}
	if in.Spot != nil {
		in, out := &in.Spot, &out.Spot
		*out = new(SpotSpec)
		**out = **in
	}
	if in.NodeLabels != nil {
		in, out := &in.NodeLabels, &out.NodeLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NodeTaints != nil {
		in, out := &in.NodeTaints, &out.NodeTaints
		*out = make([]corev1.Taint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResourceTags != nil {
		in, out := &in.ResourceTags, &out.ResourceTags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Prewarm != nil {
		in, out := &in.Prewarm, &out.Prewarm
		*out = new(PrewarmSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ProvisioningTimeout != nil {
		in, out := &in.ProvisioningTimeout, &out.ProvisioningTimeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.ResourceNotFoundRequeueInterval != nil {
		in, out := &in.ResourceNotFoundRequeueInterval, &out.ResourceNotFoundRequeueInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.StatusNotAvailableRequeueInterval != nil {
		in, out := &in.StatusNotAvailableRequeueInterval, &out.StatusNotAvailableRequeueInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.NoNodesReadyRequeueInterval != nil {
		in, out := &in.NoNodesReadyRequeueInterval, &out.NoNodesReadyRequeueInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.NodesReadyRequeueInterval != nil {
		in, out := &in.NodesReadyRequeueInterval, &out.NodesReadyRequeueInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.ErrorRequeueInterval != nil {
		in, out := &in.ErrorRequeueInterval, &out.ErrorRequeueInterval
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.MinRequiredReplicasWhenMinNodesZero != nil {
		in, out := &in.MinRequiredReplicasWhenMinNodesZero, &out.MinRequiredReplicasWhenMinNodesZero
		*out = new(int32)
		**out = **in
	}
	if in.BootstrapConfigRef != nil {
		in, out := &in.BootstrapConfigRef, &out.BootstrapConfigRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.AutoscalerEnabled != nil {
		in, out := &in.AutoscalerEnabled, &out.AutoscalerEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ScaleDownOnSuspend != nil {
		in, out := &in.ScaleDownOnSuspend, &out.ScaleDownOnSuspend
		*out = new(bool)
		**out = **in
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(AzureNodePoolSpec)
		**out = **in
	}
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(AWSNodePoolSpec)
		**out = **in
	}
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = new(GCPNodePoolSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodePoolSpec.
func (in *NodePoolSpec) DeepCopy() *NodePoolSpec {
	if in == nil {
		return nil
	}
	out := new(NodePoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearchCatalogSpec) DeepCopyInto(out *OpenSearchCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearchCatalogSpec.
func (in *OpenSearchCatalogSpec) DeepCopy() *OpenSearchCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(OpenSearchCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorNodePoolDefaultsSpec) DeepCopyInto(out *OperatorNodePoolDefaultsSpec) {
	*out = *in
	if in.DefaultMinNodes != nil {
		in, out := &in.DefaultMinNodes, &out.DefaultMinNodes
		*out = new(int32)
		**out = **in
	}
	if in.DefaultMaxNodes != nil {
		in, out := &in.DefaultMaxNodes, &out.DefaultMaxNodes
		*out = new(int32)
		**out = **in
	}
	if in.DefaultOSDiskGB != nil {
		in, out := &in.DefaultOSDiskGB, &out.DefaultOSDiskGB
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorNodePoolDefaultsSpec.
func (in *OperatorNodePoolDefaultsSpec) DeepCopy() *OperatorNodePoolDefaultsSpec {
	if in == nil {
		return nil
	}
	out := new(OperatorNodePoolDefaultsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OracleCatalogSpec) DeepCopyInto(out *OracleCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.ConnectionPasswordSecret != nil {
		in, out := &in.ConnectionPasswordSecret, &out.ConnectionPasswordSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OracleCatalogSpec.
func (in *OracleCatalogSpec) DeepCopy() *OracleCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(OracleCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PinotCatalogSpec) DeepCopyInto(out *PinotCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PinotCatalogSpec.
func (in *PinotCatalogSpec) DeepCopy() *PinotCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(PinotCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgresCatalogSpec) DeepCopyInto(out *PostgresCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.ConnectionPasswordSecret != nil {
		in, out := &in.ConnectionPasswordSecret, &out.ConnectionPasswordSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgresCatalogSpec.
func (in *PostgresCatalogSpec) DeepCopy() *PostgresCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(PostgresCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrewarmSpec) DeepCopyInto(out *PrewarmSpec) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = new(int32)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrewarmSpec.
func (in *PrewarmSpec) DeepCopy() *PrewarmSpec {
	if in == nil {
		return nil
	}
	out := new(PrewarmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusCatalogSpec) DeepCopyInto(out *PrometheusCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusCatalogSpec.
func (in *PrometheusCatalogSpec) DeepCopy() *PrometheusCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(PrometheusCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisCatalogSpec) DeepCopyInto(out *RedisCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisCatalogSpec.
func (in *RedisCatalogSpec) DeepCopy() *RedisCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(RedisCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedshiftCatalogSpec) DeepCopyInto(out *RedshiftCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.ConnectionPasswordSecret != nil {
		in, out := &in.ConnectionPasswordSecret, &out.ConnectionPasswordSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedshiftCatalogSpec.
func (in *RedshiftCatalogSpec) DeepCopy() *RedshiftCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(RedshiftCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingUpdateStrategySpec) DeepCopyInto(out *RollingUpdateStrategySpec) {
	*out = *in
	if in.MaxSurge != nil {
		in, out := &in.MaxSurge, &out.MaxSurge
		*out = new(intstr.IntOrString)
		**out = **in
	}
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(intstr.IntOrString)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingUpdateStrategySpec.
func (in *RollingUpdateStrategySpec) DeepCopy() *RollingUpdateStrategySpec {
	if in == nil {
		return nil
	}
	out := new(RollingUpdateStrategySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutPolicySpec) DeepCopyInto(out *RolloutPolicySpec) {
	*out = *in
	if in.RevisionHistoryLimit != nil {
		in, out := &in.RevisionHistoryLimit, &out.RevisionHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.RollingUpdateStrategy != nil {
		in, out := &in.RollingUpdateStrategy, &out.RollingUpdateStrategy
		*out = new(RollingUpdateStrategySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutPolicySpec.
func (in *RolloutPolicySpec) DeepCopy() *RolloutPolicySpec {
	if in == nil {
		return nil
	}
	out := new(RolloutPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoutingSpec) DeepCopyInto(out *RoutingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoutingSpec.
func (in *RoutingSpec) DeepCopy() *RoutingSpec {
	if in == nil {
		return nil
	}
	out := new(RoutingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SQLServerCatalogSpec) DeepCopyInto(out *SQLServerCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.ConnectionPasswordSecret != nil {
		in, out := &in.ConnectionPasswordSecret, &out.ConnectionPasswordSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SQLServerCatalogSpec.
func (in *SQLServerCatalogSpec) DeepCopy() *SQLServerCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(SQLServerCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretMountSpec) DeepCopyInto(out *SecretMountSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretMountSpec.
func (in *SecretMountSpec) DeepCopy() *SecretMountSpec {
	if in == nil {
		return nil
	}
	out := new(SecretMountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountSpec) DeepCopyInto(out *ServiceAccountSpec) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(bool)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountSpec.
func (in *ServiceAccountSpec) DeepCopy() *ServiceAccountSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceMonitorRoleSpec) DeepCopyInto(out *ServiceMonitorRoleSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceMonitorRoleSpec.
func (in *ServiceMonitorRoleSpec) DeepCopy() *ServiceMonitorRoleSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceMonitorRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceMonitorSpec) DeepCopyInto(out *ServiceMonitorSpec) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Coordinator != nil {
		in, out := &in.Coordinator, &out.Coordinator
		*out = new(ServiceMonitorRoleSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Worker != nil {
		in, out := &in.Worker, &out.Worker
		*out = new(ServiceMonitorRoleSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceMonitorSpec.
func (in *ServiceMonitorSpec) DeepCopy() *ServiceMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionLimits) DeepCopyInto(out *SessionLimits) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionLimits.
func (in *SessionLimits) DeepCopy() *SessionLimits {
	if in == nil {
		return nil
	}
	out := new(SessionLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SingleStoreCatalogSpec) DeepCopyInto(out *SingleStoreCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.ConnectionPasswordSecret != nil {
		in, out := &in.ConnectionPasswordSecret, &out.ConnectionPasswordSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SingleStoreCatalogSpec.
func (in *SingleStoreCatalogSpec) DeepCopy() *SingleStoreCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(SingleStoreCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnowflakeCatalogSpec) DeepCopyInto(out *SnowflakeCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.PasswordSecret != nil {
		in, out := &in.PasswordSecret, &out.PasswordSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnowflakeCatalogSpec.
func (in *SnowflakeCatalogSpec) DeepCopy() *SnowflakeCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(SnowflakeCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpotSpec) DeepCopyInto(out *SpotSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpotSpec.
func (in *SpotSpec) DeepCopy() *SpotSpec {
	if in == nil {
		return nil
	}
	out := new(SpotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemCatalogSpec) DeepCopyInto(out *SystemCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemCatalogSpec.
func (in *SystemCatalogSpec) DeepCopy() *SystemCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(SystemCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSSpec) DeepCopyInto(out *TLSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSSpec.
func (in *TLSSpec) DeepCopy() *TLSSpec {
	if in == nil {
		return nil
	}
	out := new(TLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TPCDSCatalogSpec) DeepCopyInto(out *TPCDSCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TPCDSCatalogSpec.
func (in *TPCDSCatalogSpec) DeepCopy() *TPCDSCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(TPCDSCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TPCHCatalogSpec) DeepCopyInto(out *TPCHCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TPCHCatalogSpec.
func (in *TPCHCatalogSpec) DeepCopy() *TPCHCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(TPCHCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThriftCatalogSpec) DeepCopyInto(out *ThriftCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThriftCatalogSpec.
func (in *ThriftCatalogSpec) DeepCopy() *ThriftCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(ThriftCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrinoControlAuthSpec) DeepCopyInto(out *TrinoControlAuthSpec) {
	*out = *in
	if in.PasswordSecret != nil {
		in, out := &in.PasswordSecret, &out.PasswordSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrinoControlAuthSpec.
func (in *TrinoControlAuthSpec) DeepCopy() *TrinoControlAuthSpec {
	if in == nil {
		return nil
	}
	out := new(TrinoControlAuthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerticaCatalogSpec) DeepCopyInto(out *VerticaCatalogSpec) {
	*out = *in
	in.CatalogPropertySecretRefs.DeepCopyInto(&out.CatalogPropertySecretRefs)
	if in.ConnectionPasswordSecret != nil {
		in, out := &in.ConnectionPasswordSecret, &out.ConnectionPasswordSecret
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerticaCatalogSpec.
func (in *VerticaCatalogSpec) DeepCopy() *VerticaCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(VerticaCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WakeState) DeepCopyInto(out *WakeState) {
	*out = *in
	in.ExpiresAt.DeepCopyInto(&out.ExpiresAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WakeState.
func (in *WakeState) DeepCopy() *WakeState {
	if in == nil {
		return nil
	}
	out := new(WakeState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerHelmConfigSpec) DeepCopyInto(out *WorkerHelmConfigSpec) {
	*out = *in
	if in.GracefulShutdown != nil {
		in, out := &in.GracefulShutdown, &out.GracefulShutdown
		*out = new(GracefulShutdownSpec)
		**out = **in
	}
	if in.SecretMounts != nil {
		in, out := &in.SecretMounts, &out.SecretMounts
		*out = make([]SecretMountSpec, len(*in))
		copy(*out, *in)
	}
	if in.AdditionalConfigFiles != nil {
		in, out := &in.AdditionalConfigFiles, &out.AdditionalConfigFiles
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]corev1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerHelmConfigSpec.
func (in *WorkerHelmConfigSpec) DeepCopy() *WorkerHelmConfigSpec {
	if in == nil {
		return nil
	}
	out := new(WorkerHelmConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XTrinode) DeepCopyInto(out *XTrinode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XTrinode.
func (in *XTrinode) DeepCopy() *XTrinode {
	if in == nil {
		return nil
	}
	out := new(XTrinode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XTrinode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XTrinodeCatalog) DeepCopyInto(out *XTrinodeCatalog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XTrinodeCatalog.
func (in *XTrinodeCatalog) DeepCopy() *XTrinodeCatalog {
	if in == nil {
		return nil
	}
	out := new(XTrinodeCatalog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XTrinodeCatalog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XTrinodeCatalogConnector) DeepCopyInto(out *XTrinodeCatalogConnector) {
	*out = *in
	if in.BigQuery != nil {
		in, out := &in.BigQuery, &out.BigQuery
		*out = new(BigQueryCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.BlackHole != nil {
		in, out := &in.BlackHole, &out.BlackHole
		*out = new(BlackHoleCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Cassandra != nil {
		in, out := &in.Cassandra, &out.Cassandra
		*out = new(CassandraCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ClickHouse != nil {
		in, out := &in.ClickHouse, &out.ClickHouse
		*out = new(ClickHouseCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DeltaLake != nil {
		in, out := &in.DeltaLake, &out.DeltaLake
		*out = new(DeltaLakeCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Druid != nil {
		in, out := &in.Druid, &out.Druid
		*out = new(DruidCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DuckDB != nil {
		in, out := &in.DuckDB, &out.DuckDB
		*out = new(DuckDBCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Elasticsearch != nil {
		in, out := &in.Elasticsearch, &out.Elasticsearch
		*out = new(ElasticsearchCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Exasol != nil {
		in, out := &in.Exasol, &out.Exasol
		*out = new(ExasolCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Faker != nil {
		in, out := &in.Faker, &out.Faker
		*out = new(FakerCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.GoogleSheets != nil {
		in, out := &in.GoogleSheets, &out.GoogleSheets
		*out = new(GoogleSheetsCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Hive != nil {
		in, out := &in.Hive, &out.Hive
		*out = new(HiveCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Hudi != nil {
		in, out := &in.Hudi, &out.Hudi
		*out = new(HudiCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Iceberg != nil {
		in, out := &in.Iceberg, &out.Iceberg
		*out = new(IcebergCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Ignite != nil {
		in, out := &in.Ignite, &out.Ignite
		*out = new(IgniteCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.JMX != nil {
		in, out := &in.JMX, &out.JMX
		*out = new(JMXCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Kafka != nil {
		in, out := &in.Kafka, &out.Kafka
		*out = new(KafkaCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Lakehouse != nil {
		in, out := &in.Lakehouse, &out.Lakehouse
		*out = new(LakehouseCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Loki != nil {
		in, out := &in.Loki, &out.Loki
		*out = new(LokiCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MariaDB != nil {
		in, out := &in.MariaDB, &out.MariaDB
		*out = new(MariaDBCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(MemoryCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MongoDB != nil {
		in, out := &in.MongoDB, &out.MongoDB
		*out = new(MongoDBCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MySQL != nil {
		in, out := &in.MySQL, &out.MySQL
		*out = new(MySQLCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OpenSearch != nil {
		in, out := &in.OpenSearch, &out.OpenSearch
		*out = new(OpenSearchCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Oracle != nil {
		in, out := &in.Oracle, &out.Oracle
		*out = new(OracleCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Pinot != nil {
		in, out := &in.Pinot, &out.Pinot
		*out = new(PinotCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Postgres != nil {
		in, out := &in.Postgres, &out.Postgres
		*out = new(PostgresCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Prometheus != nil {
		in, out := &in.Prometheus, &out.Prometheus
		*out = new(PrometheusCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Redis != nil {
		in, out := &in.Redis, &out.Redis
		*out = new(RedisCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Redshift != nil {
		in, out := &in.Redshift, &out.Redshift
		*out = new(RedshiftCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SingleStore != nil {
		in, out := &in.SingleStore, &out.SingleStore
		*out = new(SingleStoreCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Snowflake != nil {
		in, out := &in.Snowflake, &out.Snowflake
		*out = new(SnowflakeCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SQLServer != nil {
		in, out := &in.SQLServer, &out.SQLServer
		*out = new(SQLServerCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.System != nil {
		in, out := &in.System, &out.System
		*out = new(SystemCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Thrift != nil {
		in, out := &in.Thrift, &out.Thrift
		*out = new(ThriftCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TPCDS != nil {
		in, out := &in.TPCDS, &out.TPCDS
		*out = new(TPCDSCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TPCH != nil {
		in, out := &in.TPCH, &out.TPCH
		*out = new(TPCHCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Vertica != nil {
		in, out := &in.Vertica, &out.Vertica
		*out = new(VerticaCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Custom != nil {
		in, out := &in.Custom, &out.Custom
		*out = new(CustomCatalogSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XTrinodeCatalogConnector.
func (in *XTrinodeCatalogConnector) DeepCopy() *XTrinodeCatalogConnector {
	if in == nil {
		return nil
	}
	out := new(XTrinodeCatalogConnector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XTrinodeCatalogList) DeepCopyInto(out *XTrinodeCatalogList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]XTrinodeCatalog, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XTrinodeCatalogList.
func (in *XTrinodeCatalogList) DeepCopy() *XTrinodeCatalogList {
	if in == nil {
		return nil
	}
	out := new(XTrinodeCatalogList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XTrinodeCatalogList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XTrinodeCatalogSpec) DeepCopyInto(out *XTrinodeCatalogSpec) {
	*out = *in
	in.Connector.DeepCopyInto(&out.Connector)
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XTrinodeCatalogSpec.
func (in *XTrinodeCatalogSpec) DeepCopy() *XTrinodeCatalogSpec {
	if in == nil {
		return nil
	}
	out := new(XTrinodeCatalogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XTrinodeCatalogStatus) DeepCopyInto(out *XTrinodeCatalogStatus) {
	*out = *in
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XTrinodeCatalogStatus.
func (in *XTrinodeCatalogStatus) DeepCopy() *XTrinodeCatalogStatus {
	if in == nil {
		return nil
	}
	out := new(XTrinodeCatalogStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XTrinodeList) DeepCopyInto(out *XTrinodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]XTrinode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XTrinodeList.
func (in *XTrinodeList) DeepCopy() *XTrinodeList {
	if in == nil {
		return nil
	}
	out := new(XTrinodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *XTrinodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XTrinodeSpec) DeepCopyInto(out *XTrinodeSpec) {
	*out = *in
	if in.MaxWorkers != nil {
		in, out := &in.MaxWorkers, &out.MaxWorkers
		*out = new(int32)
		**out = **in
	}
	if in.MinWorkers != nil {
		in, out := &in.MinWorkers, &out.MinWorkers
		*out = new(int32)
		**out = **in
	}
	if in.AutoSuspendAfter != nil {
		in, out := &in.AutoSuspendAfter, &out.AutoSuspendAfter
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.WakeMinWorkers != nil {
		in, out := &in.WakeMinWorkers, &out.WakeMinWorkers
		*out = new(int32)
		**out = **in
	}
	if in.WakeTTL != nil {
		in, out := &in.WakeTTL, &out.WakeTTL
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.NodePool != nil {
		in, out := &in.NodePool, &out.NodePool
		*out = new(NodePoolSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Routing != nil {
		in, out := &in.Routing, &out.Routing
		*out = new(RoutingSpec)
		**out = **in
	}
	if in.CatalogSelector != nil {
		in, out := &in.CatalogSelector, &out.CatalogSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomConfigMaps != nil {
		in, out := &in.CustomConfigMaps, &out.CustomConfigMaps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(LimitsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ValuesOverlay != nil {
		in, out := &in.ValuesOverlay, &out.ValuesOverlay
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.TrinoControlAuth != nil {
		in, out := &in.TrinoControlAuth, &out.TrinoControlAuth
		*out = new(TrinoControlAuthSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.FaultTolerantExecution != nil {
		in, out := &in.FaultTolerantExecution, &out.FaultTolerantExecution
		*out = new(FaultTolerantExecutionSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.KEDA != nil {
		in, out := &in.KEDA, &out.KEDA
		*out = new(KEDASpec)
		(*in).DeepCopyInto(*out)
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSSpec)
		**out = **in
	}
	if in.HelmChartConfig != nil {
		in, out := &in.HelmChartConfig, &out.HelmChartConfig
		*out = new(HelmChartConfigSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OperatorNodePoolDefaults != nil {
		in, out := &in.OperatorNodePoolDefaults, &out.OperatorNodePoolDefaults
		*out = new(OperatorNodePoolDefaultsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.RolloutPolicy != nil {
		in, out := &in.RolloutPolicy, &out.RolloutPolicy
		*out = new(RolloutPolicySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XTrinodeSpec.
func (in *XTrinodeSpec) DeepCopy() *XTrinodeSpec {
	if in == nil {
		return nil
	}
	out := new(XTrinodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *XTrinodeStatus) DeepCopyInto(out *XTrinodeStatus) {
	*out = *in
	if in.LastActivity != nil {
		in, out := &in.LastActivity, &out.LastActivity
		*out = (*in).DeepCopy()
	}
	if in.ObservedCatalogs != nil {
		in, out := &in.ObservedCatalogs, &out.ObservedCatalogs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Wake != nil {
		in, out := &in.Wake, &out.Wake
		*out = new(WakeState)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new XTrinodeStatus.
func (in *XTrinodeStatus) DeepCopy() *XTrinodeStatus {
	if in == nil {
		return nil
	}
	out := new(XTrinodeStatus)
	in.DeepCopyInto(out)
	return out
}
