apiVersion: v2
name: xtrinode-observability
description: XTrinode observability stack with Prometheus and Vector
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - prometheus
  - vector
  - observability
  - xtrinode
home: https://github.com/xtrinode/xtrinode
sources:
  - https://github.com/xtrinode/xtrinode
maintainers:
  - name: XTrinode
    email: xtrinode@gmail.com
dependencies:
  - name: kube-prometheus-stack
    alias: prometheus-stack
    version: 85.2.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-stack.enabled
  - name: xtrinode-vector
    alias: vector
    version: "0.1.0"
    repository: "file://../xtrinode-vector"
    condition: vector.enabled
