package controllers

import (
	"context"

	"github.com/go-logr/logr"
	appsv1 "k8s.io/api/apps/v1"
	autoscalingv2 "k8s.io/api/autoscaling/v2"
	corev1 "k8s.io/api/core/v1"
	discoveryv1 "k8s.io/api/discovery/v1"
	networkingv1 "k8s.io/api/networking/v1"
	policyv1 "k8s.io/api/policy/v1"
	"k8s.io/apimachinery/pkg/api/meta"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/builder"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller"
	"sigs.k8s.io/controller-runtime/pkg/event"
	"sigs.k8s.io/controller-runtime/pkg/handler"
	"sigs.k8s.io/controller-runtime/pkg/predicate"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"

	kedav1alpha1 "github.com/kedacore/keda/v2/apis/keda/v1alpha1"
	analyticsv1 "github.com/xtrinode/xtrinode/api/v1"
	"github.com/xtrinode/xtrinode/internal/config"
)

type xtrinodeRequestMapper func(client.Client, context.Context, client.Object, logr.Logger) []reconcile.Request

func (r *XTrinodeReconciler) SetupWithManager(mgr ctrl.Manager, maxConcurrentReconciles int) error {
	controllerBuilder := ctrl.NewControllerManagedBy(mgr).
		WithOptions(controller.Options{
			MaxConcurrentReconciles: maxConcurrentReconciles,
		}).
		For(&analyticsv1.XTrinode{}, builder.WithPredicates(xtrinodePredicate())).
		// Watch owned runtime children so manual drift/deletes are repaired without waiting
		// for an unrelated XTrinode or catalog event. Deployment readiness counters are
		// included; other high-churn status-only updates stay filtered. ConfigMaps and
		// Secrets use ResourceVersion to catch data edits.
		Owns(&appsv1.Deployment{}, builder.WithPredicates(ownedDeploymentPredicate())).
		Owns(&corev1.Service{}, builder.WithPredicates(ownedResourcePredicate())).
		Owns(&corev1.ServiceAccount{}, builder.WithPredicates(ownedResourcePredicate())).
		Owns(&corev1.ConfigMap{}, builder.WithPredicates(predicate.ResourceVersionChangedPredicate{})).
		Owns(&corev1.Secret{}, builder.WithPredicates(predicate.ResourceVersionChangedPredicate{})).
		Owns(&policyv1.PodDisruptionBudget{}, builder.WithPredicates(ownedResourcePredicate())).
		Owns(&networkingv1.Ingress{}, builder.WithPredicates(ownedResourcePredicate())).
		Owns(&networkingv1.NetworkPolicy{}, builder.WithPredicates(ownedResourcePredicate())).
		Owns(&autoscalingv2.HorizontalPodAutoscaler{}, builder.WithPredicates(ownedResourcePredicate())).
		Owns(&kedav1alpha1.ScaledObject{}, builder.WithPredicates(ownedResourcePredicate())).
		Owns(&kedav1alpha1.TriggerAuthentication{}, builder.WithPredicates(ownedResourcePredicate())).
		// Namespace guardrails are shared per namespace rather than owned by a
		// single XTrinode, so manual drift must fan out to all runtimes in the namespace.
		Watches(
			&corev1.ResourceQuota{},
			r.enqueueXTrinodeRequests(namespaceGuardrailToXTrinodes),
			builder.WithPredicates(namespaceGuardrailResourcePredicate(isNamespaceResourceQuota)),
		).
		Watches(
			&corev1.LimitRange{},
			r.enqueueXTrinodeRequests(namespaceGuardrailToXTrinodes),
			builder.WithPredicates(namespaceGuardrailResourcePredicate(isNamespaceLimitRange)),
		).
		// Watch ConfigMaps matching trino-catalog-* pattern (generated by XTrinodeCatalog controller).
		// Catalog membership is selector-driven, but selected catalog data changes must refresh rollouts.
		Watches(
			&corev1.ConfigMap{},
			r.enqueueXTrinodeRequests(catalogConfigMapToXTrinodes),
			builder.WithPredicates(
				predicate.And(
					predicate.NewPredicateFuncs(isCatalogConfigMap),
					predicate.ResourceVersionChangedPredicate{},
				),
			),
		).
		// Watch the shared gateway route ConfigMap. This is not owned by any one XTrinode,
		// so route ConfigMap deletion or manual route drift must fan out to all runtimes.
		Watches(
			&corev1.ConfigMap{},
			r.enqueueXTrinodeRequests(gatewayConfigMapToXTrinodes),
			builder.WithPredicates(
				predicate.And(
					predicate.NewPredicateFuncs(isGatewayRouteConfigMap),
					predicate.ResourceVersionChangedPredicate{},
				),
			),
		).
		// Watch external ConfigMaps referenced by runtime mounts or envFrom. These are not
		// owned by the operator, but their content is part of the effective pod runtime.
		Watches(
			&corev1.ConfigMap{},
			r.enqueueXTrinodeRequests(externalConfigMapToXTrinodes),
			builder.WithPredicates(predicate.ResourceVersionChangedPredicate{}),
		).
		// Watch Secrets referenced by selected catalogs. Catalog password Secrets are injected
		// as env vars, and mounted Secret dependencies are hashed into rollout inputs, so value
		// changes must reconcile XTrinodes to refresh rollout hashes.
		Watches(
			&corev1.Secret{},
			r.enqueueXTrinodeRequests(secretToXTrinodes),
			builder.WithPredicates(predicate.ResourceVersionChangedPredicate{}),
		).
		// EndpointSlice changes can make an otherwise Ready coordinator unroutable
		// without a Deployment status change.
		Watches(
			&discoveryv1.EndpointSlice{},
			r.enqueueXTrinodeRequests(endpointSliceToXTrinodes),
			builder.WithPredicates(predicate.ResourceVersionChangedPredicate{}),
		)

	controllerBuilder = r.addServiceMonitorWatchIfAvailable(mgr, controllerBuilder)
	controllerBuilder = r.addNodePoolWatchesIfAvailable(mgr, controllerBuilder)
	return controllerBuilder.Complete(r)
}

func (r *XTrinodeReconciler) enqueueXTrinodeRequests(mapper xtrinodeRequestMapper) handler.EventHandler {
	return handler.EnqueueRequestsFromMapFunc(func(ctx context.Context, obj client.Object) []reconcile.Request {
		return mapper(r.Client, ctx, obj, ctrl.LoggerFrom(ctx))
	})
}

func (r *XTrinodeReconciler) addServiceMonitorWatchIfAvailable(mgr ctrl.Manager, controllerBuilder *builder.Builder) *builder.Builder {
	gvk := serviceMonitorGVK()
	if _, err := mgr.GetRESTMapper().RESTMapping(gvk.GroupKind(), gvk.Version); err != nil {
		if meta.IsNoMatchError(err) {
			ctrl.Log.WithName("xtrinode-controller").V(1).Info("Skipping ServiceMonitor watch because the CRD is not installed")
		} else {
			ctrl.Log.WithName("xtrinode-controller").Error(err, "Skipping ServiceMonitor watch because REST mapping failed")
		}
		return controllerBuilder
	}

	serviceMonitor := &unstructured.Unstructured{}
	serviceMonitor.SetGroupVersionKind(gvk)
	return controllerBuilder.Watches(
		serviceMonitor,
		r.enqueueXTrinodeRequests(serviceMonitorToXTrinodes),
		builder.WithPredicates(ownedResourcePredicate()),
	)
}

func (r *XTrinodeReconciler) addNodePoolWatchesIfAvailable(mgr ctrl.Manager, controllerBuilder *builder.Builder) *builder.Builder {
	for _, gvk := range nodePoolWatchGVKs() {
		if _, err := mgr.GetRESTMapper().RESTMapping(gvk.GroupKind(), gvk.Version); err != nil {
			if meta.IsNoMatchError(err) {
				ctrl.Log.WithName("xtrinode-controller").V(1).Info("Skipping node pool watch because the CRD is not installed", "gvk", gvk.String())
			} else {
				ctrl.Log.WithName("xtrinode-controller").Error(err, "Skipping node pool watch because REST mapping failed", "gvk", gvk.String())
			}
			continue
		}

		resource := &unstructured.Unstructured{}
		resource.SetGroupVersionKind(gvk)
		controllerBuilder = controllerBuilder.Watches(
			resource,
			r.enqueueXTrinodeRequests(xtrinodeOwnerReferenceToXTrinodes),
			builder.WithPredicates(
				predicate.And(
					predicate.NewPredicateFuncs(hasXTrinodeOwnerReference),
					predicate.ResourceVersionChangedPredicate{},
				),
			),
		)
	}
	return controllerBuilder
}

func serviceMonitorGVK() schema.GroupVersionKind {
	return schema.GroupVersionKind{
		Group:   "monitoring.coreos.com",
		Version: "v1",
		Kind:    "ServiceMonitor",
	}
}

func nodePoolWatchGVKs() []schema.GroupVersionKind {
	return []schema.GroupVersionKind{
		getMachineResourceGVK(false),
		getMachineResourceGVK(true),
		getInfrastructureTemplateGVK("azure", true),
		getInfrastructureTemplateGVK("aws", false),
		getInfrastructureTemplateGVK("gcp", false),
		getManagedInfrastructureGVK("azure"),
		getManagedInfrastructureGVK("aws"),
		getManagedInfrastructureGVK("gcp"),
	}
}

func hasXTrinodeOwnerReference(obj client.Object) bool {
	for _, owner := range obj.GetOwnerReferences() {
		if owner.APIVersion == analyticsv1.GroupVersion.String() && owner.Kind == "XTrinode" && owner.Name != "" {
			return true
		}
	}
	return false
}

func ownedResourcePredicate() predicate.Predicate {
	return predicate.Or(
		predicate.GenerationChangedPredicate{},
		predicate.AnnotationChangedPredicate{},
		predicate.LabelChangedPredicate{},
	)
}

func namespaceGuardrailResourcePredicate(match func(client.Object) bool) predicate.Predicate {
	return predicate.And(
		predicate.NewPredicateFuncs(match),
		ownedResourcePredicate(),
	)
}

func ownedDeploymentPredicate() predicate.Predicate {
	base := ownedResourcePredicate()
	return predicate.Funcs{
		CreateFunc: func(e event.CreateEvent) bool {
			return base.Create(e)
		},
		DeleteFunc: func(e event.DeleteEvent) bool {
			return base.Delete(e)
		},
		UpdateFunc: func(e event.UpdateEvent) bool {
			if base.Update(e) {
				return true
			}
			oldDeployment, okOld := e.ObjectOld.(*appsv1.Deployment)
			newDeployment, okNew := e.ObjectNew.(*appsv1.Deployment)
			if !okOld || !okNew {
				return false
			}
			return deploymentRuntimeStatusChanged(oldDeployment.Status, newDeployment.Status)
		},
		GenericFunc: func(e event.GenericEvent) bool {
			return base.Generic(e)
		},
	}
}

func deploymentRuntimeStatusChanged(oldStatus, newStatus appsv1.DeploymentStatus) bool {
	return oldStatus.ObservedGeneration != newStatus.ObservedGeneration ||
		oldStatus.Replicas != newStatus.Replicas ||
		oldStatus.UpdatedReplicas != newStatus.UpdatedReplicas ||
		oldStatus.ReadyReplicas != newStatus.ReadyReplicas ||
		oldStatus.AvailableReplicas != newStatus.AvailableReplicas ||
		oldStatus.UnavailableReplicas != newStatus.UnavailableReplicas
}

// xtrinodePredicate returns a predicate that triggers reconciliation for:
// - Spec changes (generation increment)
// - Deletion transitions
// - Command annotation changes (resume/suspend/auto-suspend) including timestamps and wake params
// Note: Annotation-based commands are processed via ProcessCommands() in reconcile
func xtrinodePredicate() predicate.Predicate {
	// All annotations that can carry or modify a command.
	// Include *RequestedAt timestamps and wake param annotations so that:
	//   (a) retrying an invalid command by fixing wake params triggers a reconcile, and
	//   (b) timestamp-only updates (e.g. re-issuing the same command) trigger a reconcile.
	commandAnnotations := []string{
		config.ResumeRequestedAnnotation,
		config.ResumeRequestedAtAnnotation,
		config.SuspendRequestedAnnotation,
		config.SuspendRequestedAtAnnotation,
		config.AutoSuspendRequestedAnnotation,
		config.AutoSuspendRequestedAtAnnotation,
		config.WakeMinWorkersAnnotation,
		config.WakeTTLAnnotation,
	}

	return predicate.Funcs{
		CreateFunc: func(e event.CreateEvent) bool { return true },
		DeleteFunc: func(e event.DeleteEvent) bool { return true },
		UpdateFunc: func(e event.UpdateEvent) bool {
			oldT, ok1 := e.ObjectOld.(*analyticsv1.XTrinode)
			newT, ok2 := e.ObjectNew.(*analyticsv1.XTrinode)
			if !ok1 || !ok2 {
				return true
			}

			// Spec change (generation increment)
			if oldT.GetGeneration() != newT.GetGeneration() {
				return true
			}

			// Deletion start
			if (oldT.DeletionTimestamp == nil) != (newT.DeletionTimestamp == nil) {
				return true
			}

			// Command annotation changes
			oldAnnotations := oldT.GetAnnotations()
			newAnnotations := newT.GetAnnotations()
			for _, key := range commandAnnotations {
				oldVal := oldAnnotations[key]
				newVal := newAnnotations[key]
				if oldVal != newVal {
					return true // Command annotation changed
				}
			}

			return false
		},
	}
}
