apiVersion: analytics.xtrinode.io/v1
kind: XTrinode
metadata:
  name: postgres-query
  namespace: team-a
spec:
  size: s
  minWorkers: 0
  maxWorkers: 2
  suspended: false
  routing:
    header: X-Trino-XTrinode=postgres-query
    routingGroup: postgres-query
  catalogSelector:
    matchLabels:
      team: team-a
      catalog-type: postgres
  valuesOverlay:
    coordinator:
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: "2"
          memory: 2Gi
    worker:
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: "2"
          memory: 2Gi
