{{- $gatewayRedisEnabled := or .Values.gateway.redis.enabled .Values.redis.enabled }}
{{- $createRedisSecret := or (and .Values.redis.enabled .Values.redis.auth.enabled (not .Values.redis.auth.existingSecret) .Values.redis.auth.password) (and $gatewayRedisEnabled .Values.gateway.redis.password (not .Values.gateway.redis.existingSecret) (not .Values.redis.auth.existingSecret)) }}
{{- if $createRedisSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xtrinode-gateway.redisSecretName" . }}
  namespace: {{ include "xtrinode-gateway.namespace" . }}
  labels:
    {{- include "xtrinode-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{ coalesce .Values.gateway.redis.existingSecretKey .Values.redis.auth.existingSecretKey "redis-password" }}: {{ coalesce .Values.gateway.redis.password .Values.redis.auth.password | b64enc | quote }}
{{- end }}
