{{- if and .Values.rbac.create .Values.rbac.xtrinodeRead .Values.gateway.ui.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "xtrinode-gateway.fullname" . }}-xtrinode-reader
  labels:
    {{- include "xtrinode-gateway.labels" . | nindent 4 }}
rules:
- apiGroups: ["analytics.xtrinode.io"]
  resources: ["xtrinodes"]
  verbs: ["get", "list", "watch"]
{{- end }}
