{{- if and .Values.apiServer.auth.enabled (not .Values.apiServer.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xtrinode-api-server.authSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "xtrinode-api-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.apiServer.auth.secretKey | default "token" }}: {{ required "apiServer.auth.token is required when apiServer.auth.enabled=true and apiServer.auth.existingSecret is empty" .Values.apiServer.auth.token | quote }}
{{- end }}
