{{- if and .Values.enabled .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xtrinode-vector.fullname" . }}-metrics
  namespace: {{ include "xtrinode-vector.namespace" . }}
  labels:
    {{- include "xtrinode-vector.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  selector:
    {{- include "xtrinode-vector.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
